name: Docker build and push

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        #with:
        #  token: ${{ secrets.TOKEN }}
      - name: Build image
        run: |
          docker build -t docker-webmin:latest -f- . <<EOF
          FROM node:14

          WORKDIR /src

          COPY package.json yarn.lock ./
          RUN yarn install

          COPY . .

          EXPOSE 8080

          CMD ["yarn", "start"]

          EOF
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}         
      - name: Push image
        run: |
          docker tag docker-webmin:latest ghcr.io/vhsec/docker-webmin:latest
          docker push ghcr.io/vhsec/docker-webmin:latest